# Site Author
author:
  name: "Hamann Lab"
  location: "578 S Shaw Lane<br>East Lansing, MI 48824"
  avatar: "logo.png"

  # Institutional affiliations
  employer: "Michigan State University"
  employer_url: "https://msu.edu/"
  department: "Department of Chemistry"
  department_url: "https://www.chemistry.msu.edu/"

  # Contact and academic profiles
  email: "hamann@msu.edu"
  googlescholar: "https://scholar.google.com/citations?user=KRBt0_AAAAAJ&hl=en"
  orcid: "https://orcid.org/0000-0001-6917-7494"
  linkedin: "https://www.linkedin.com/in/thomas-hamann-a1117954/"

  # Repository
  github: "HamannLab"
